name: Update Exit Nodes

on:
  schedule:
    - cron:  '0 * * * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: wouldnt/tor-list-action@master
        run: |
          wget https://check.torproject.org/torbulkexitlist > src/exit-nodes.txt
