name: Update Exit Nodes

on:
  schedule:
    - cron:  '0 * * * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: wouldnt/tor-list-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: "main"
          file: "./data/exit-nodes.json"
          committer_name: ${{ secrets.COMMITTER_NAME }}
          committer_email: ${{ secrets.COMMITTER_EMAIL }}
